# Modify Tuple Indirectly
item_1 = input("Enter your first item: ")
item_2 = input("Enter your second item: ")
item_3 = input("Enter your third item: ")
shopping_list = (item_1, item_2, item_3)
print(shopping_list)
lst = list(shopping_list)
item_4 = input("list another item: ")
item_5 = input("list another item: ")
new_list = (f"{item_4}, {item_5}")
print(new_list)
lst.append(new_list)
print(lst)
shopping_list = tuple(lst)
print(shopping_list)
print()