student_names = []
scores = []
student_name1 = input("Enter the student names: ")
student_names.append(student_name1)
score1 = int(input("Enter the student scores: "))
scores.append(score1)
student_name2 = input("Enter the student names: ")
student_names.append(student_name2)
score2 = int(input("Enter the student scores: "))
scores.append(score2)
student_name3 = input("Enter the student names: ")
student_names.append(student_name3)
score3 = int(input("Enter the student scores: "))
scores.append(score3)
print(student_names)
print(scores)
print(f"Students\tScores\n  {student_name1}\t          {score1}\n  {student_name2}\t          {score2}\n  {student_name3}\t          {score3}")